site_name: BiomationScripterLib

repo_url: https://github.com/intbio-ncl/BiomationScripterLib
repo_name: Source Code on GitHub

docs_dir: "docs"

theme:
    logo: wiki-images/Logo - Pic Only.png

    icon:
      repo: fontawesome/brands/github
      admonition:
        example: material/notebook

    name: "material"
    palette:

      - scheme: default
        toggle:
          icon: material/lightbulb
          name: Switch to dark mode
        primary: deep purple
        accent: light blue

      - scheme: slate
        toggle:
          icon: material/lightbulb-outline
          name: Switch to light mode
        primary: deep purple
        accent: light blue

plugins:
  - mkdocs-jupyter:
      include: ["*.ipynb"]
  - search

markdown_extensions:
  - admonition
  - pymdownx.details

  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
