site_name: BiomationScripterLib

repo_url: https://github.com/intbio-ncl/BiomationScripterLib
repo_name: BiomationScripter

docs_dir: "docs"

theme:
    icon:
      repo: fontawesome/brands/github
    name: "material"
    palette:

      - scheme: default
        toggle:
          icon: material/lightbulb
          name: Switch to dark mode
        primary: indigo
        accent: deep purple

      - scheme: slate
        toggle:
          icon: material/lightbulb-outline
          name: Switch to light mode
        primary: indigo
        accent: deep purple

plugins:
  - mkdocs-jupyter:
      include: ["*.ipynb"]
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
